### ISSUE TITLE
Not working with Sparkfun AST-CAN485 

### ISSUE THREAD

**Issue by m0vse** [thomasonw/avr_can#6]
Hi. 

I have a pair of Sparkfun AST-CAN485 (AT90CAN128 based) boards. When I use their provided CAN library tx/rx samples, I can successfully send/receive CAN data but it has no method of manipulating filters/mailboxes and relies on polling, so I would like (if possible) to use your library.

I tried your simple interrupt based receiver and it appears to "crash" when it starts to receive data from the remote, I have a simple led flasher in the loop function and as soon as I connect the CAN bus (connected to a simple transmitter) the LED stops flashing!

Any ideas?

Thanks

Phil

**Comment by thomasonw** [comment]
Hello.   Yes, seems the AT90 is a little different, and folks have reported problems.   If you do get it solved, make sure to post back up the fixes!

IIRC, the CAN subsystem is largely the same, except there are more mailboxes in the AT90?    Looking at what you described, I think you are on the right approach -  I would likely look into the IRQ subsystem, it could well the the IRQ handlers need to change.

**Comment by m0vse** [comment]
Yes I had come the the same conclusion. I am looking through other implementations and it looks like initialisation of the CANGIE register may be different? 

I will definitely let you know if (when) I find the problem!

**Comment by m0vse** [comment]
Well the problem was quite easy really, the ISR names are different for the AT90CAN!

Changing CAN_INT_vect to CANINT_vect fixes the problem and CAN is working great...

**Comment by thomasonw** [comment]
@m0vse   That is good news!  Thank you.   Do the compile checks work for the AT90? 

```
#if defined(__AVR_AT90CAN32__) || \
    defined(__AVR_AT90CAN64__) || \
    defined(__AVR_AT90CAN128__)
```


Perhaps adding  `#def  CAN_INT_vect   CANINT_vect `  on line 63 would fix things?

Also, was the "CAN_TOVF_vect" ok?

**Comment by m0vse** [comment]
I will try that and let you know. Yes the compile checks worked fine. Not sure about CAN_TOVF_vect but I think it is CANTOVF_vect on the AT90?

**Comment by thomasonw** [comment]
You know, perhaps another option is just add the #defines full time, forget the CPU check.   Should not cause an issue – clearly Ateml kind of missed the mark here with two slightly different names for the same thing…

**Comment by thomasonw** [comment]
@m0vse   Hello.   Just now I pushed up a potential fix, added an Ifdef to copy over the victor.   If you get a chance, could you give it a test?

**Comment by geraldjust** [comment]
Ive tested the latest version but i run into the issue of crashing to when it send out a CAN frame.

**Comment by thomasonw** [comment]
OK, ISR vectors must be resolved in the pre-processor.  So, have taken a different approach and just pushed it up.  Would you be so kind to try this one, and if it also has issues - maybe you have an idea?

**Comment by geraldjust** [comment]
well it seems to initialize ok, Once a canframe has to be send or received is when it crashes too. i will Manually try @m0vse fix to see if it fixes it or not.  I can send ya some hardware if you want to give it a try. But im looking at the datasheet so see if any other changed names pop out.

**Comment by geraldjust** [comment]
Im such a goof. So according to the AVR-GCC lib, its `CAN_INT_vect` to `CANIT_vect` not `CANINT_vect`. Also will the flag AT90CAN catch any of the processor flags. Or would `defined(__AVR_AT90CAN128__)` have to be done?

**Comment by m0vse** [comment]
Hi.

 

Sorry I have been away from this for a while. The latest changed code still doesn’t work for me. I have found that I need to add the following at the start of CANRaw::init()

 

                CLKPR  = ( 1 << CLKPCE );          // Set Clock Prescaler change enable

                CLKPR  = 0x00;

                // Setup ports

                DDRB  |= (1<<DDB1)|(1<<DDB4);

                DDRD  |= (1<<DDD5);                   // TxCan

                PORTB |= (1<<PORTB4);                                                                // set CAN_STBY high

                PORTD |= (1<<PORTD5);             // txCAN High

                PORTB &= ~(1<<PORTB4);                           // Go into normal mode (CAN_STBY low)

 

The code was taken straight from ASTCanLib and by adding this before any other code in the init() function everything seems to work OK so at worse it could go in another #ifdef I guess?

 

Thanks


Phil

**Comment by geraldjust** [comment]
Yes! for the AST can Lib they were managing the STBY pin in library rather than in code. They never assigned a actual arduino pin in the pins_arduino.h file so you need to manually pull down the pin to get the transceiver out of standby.

Not sure why it did not work for you. But i guess i only tested reading can data so the STBY pin did not come into effect.
